version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres_lyagushka}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-meta_pass}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-justlyagushka@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  
  frontend:
    container_name: frontend_container
    image: frontend:latest
    depends_on:
      - api
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=todo.com
      - NGINX_PORT=80
    networks:
      - postgres
      - api
    restart: unless-stopped

  
  
  api:
    container_name: backend_container
    image: backend:latest
    depends_on:
      - postgres
    ports:
      - "8000:80"
    networks:
      - postgres
      - api
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  api:
    driver: bridge


volumes:
    postgres:
    pgadmin:
